### ISSUE TITLE
caldavzap on a smart phone

### ISSUE THREAD

**Issue by henrythemouse** [Offerel/roundcube_caldavzap#11]
I've been testing roundcubemail out on my phone using the new elastic skin. It works really well. Of course I also had to try caldavzap out. That has quite a few problems. I was wondering if you've considered working on seeing if caldavzap could be usable on a phone?

TIA

**Comment by Offerel** [comment]
I can't do much in this case. This is a upstream issue in CalDAVZap itself. You only option would be to ask the developer of CalDAVZap to release a new version with mobile support.
