### ISSUE TITLE
Calendar is empty

### ISSUE THREAD

**Issue by winnertako** [Offerel/roundcube_caldavzap#12]
Hi,

I've installed the latest version of _caldavzap_ on my _roundcube_ server but unfortunately nothing shows up.

![Screenshot from 2019-11-04 13-23-27](https://user-images.githubusercontent.com/52783790/68124074-599f2780-ff06-11e9-9520-f2ba680d55f1.png)

My config.inc.php:

// URL to CalDAVZap
$config['caldavzap_url'] = 'plugins/caldavzap/caldavzap_0.13.2/roundcube.html';

// Domain for CalDAV server
$config['caldav_server'] = 'davical.wit-software.com';

// CalDAV Path where the DAV server resides
$config['caldav_path'] = '/caldav.php/%u/calendars/';

What I'm missing?

Thank you

**Comment by Offerel** [comment]
If, as in your case, nothing is displayed at all, please check whether there are error messages in the log files or in the browser console. In case the plugin cannot load the corresponding data, there are unfortunately many different possible reasons. Unfortunately, only a look at the log files will help. First, I would check the web console in your browser for error messages related to the plugin. Maybe also a browser plugin blocks a Javascript of the plugin, in this case you should reload the page with deactivated Browser AddOns. Additional server-side problems or misconfigurations can be found in the logfile of Roundcube or in the logfile of the webserver or of PHP.

**Comment by winnertako** [comment]
You are right, I can see one error on the web console in my browser :

![Screenshot from 2019-11-04 14-31-00](https://user-images.githubusercontent.com/52783790/68128827-5dd04280-ff10-11e9-91d8-c0fb85ec2bc0.png)

But on my web server logs I can't find any error related.

**Comment by winnertako** [comment]
I figured out what I thinks it's the cause of my problem. On plugin file configuration I have changed the caldav_path from /caldav.php/%u/calendars/' to /caldav.php/' and the error have changed to:
`https://davical.domain.com/caldav.php/username/ 401 (Unauthorized)`

Now, how can I complete the link with the calendar?

**Comment by Offerel** [comment]
Somehow my message from yesterday seems to to have disappeared. Sorry. Without knowing your exact configuration, especially from your CalDAV backend, it's hard to give a recommendation. 

From the error message you can at least see that the URL mentioned there requires authentication, but it fails. The plugin is designed to use the same credentials for the CalDAV backend as you entered for the login to Roundcube. So you have to make sure that both logins are identical. You should also pay attention to upper/lower case and use full email addresses. 

Furthermore you have to make sure that the URL is correct and that Roundcube and CalDAV backend are on the same server. So according to your example, Roundcube must also be accessible somewhere on https://davical.domain.com

**Comment by winnertako** [comment]
Sorry, I've made some changes on my last post.

I think my problem it's because in this case I have the Rouncube and Davical backend on diferent servers. 

I will try this plugin one another test case I've with the Roundcube and Davical backend on same server but with different virtual hosts. It will work on this case with two different virtual hosts? 

- https://webmail.domain.com

- https://calendar.domain.com  

Thank you for patience and help.

**Comment by Offerel** [comment]
No, this wouldn't work. This is also a crossdomain setup which isn't supported by CalDAVZap. There are several reasons, why it isn't the best idea to use crossdomain setups at all. It can work, but it would be a real pain to set it up and also if you get it to work, there can be serious security issues because of such a setup. All in all, it's a problem which is related in general to all JavaScript based things. The only way which would work is, if you can change your CalDAV Backend to send the right CORS headers. But with this you can open your server for some CORS based attacks. I cant recommend that.

**Comment by winnertako** [comment]
I've made some changes on my server and now I'm can see my davical calendar:
![Screenshot from 2019-11-06 12-53-08](https://user-images.githubusercontent.com/52783790/68299900-8ed98000-0094-11ea-92c2-168cd7e1a21b.png)

Now I've one question, Its not possible to add Attendees when I'm trying to create one event?

Thank you.

**Comment by Offerel** [comment]
No. Thats not possible with CalDAVZap.

**Comment by winnertako** [comment]
> No. Thats not possible with CalDAVZap.

Ok :( Thank you for your help :)
