### ISSUE TITLE
caldav_path for Baikal

### ISSUE THREAD

**Issue by clivey-za** [Offerel/roundcube_caldavzap#14]
Hi, 

I need help with the caldav_path for Baikal please.

The following works for Thunderbird over local network;
http://192.168.8.51/baikal/html/cal.php/calendars/user/default

I have set Baikal authentication to basic and also have rcmcarddav working using:
http://localhost:80/baikal/html/card.php/addressbooks/user/default/

I have tried various caldav_paths but am either getting a blank calendar or credential prompt.
caldav_server is localhost

**Comment by Offerel** [comment]
In that case you can try http://localhost/baikal/html/cal.php/username/principals/ or without principals and ending on slash

**Comment by clivey-za** [comment]
Sorry, seems it wasn't the caldav_path, but the caldav_server that was the issue - changing it to the IP instead of localhost worked. Thanks.

**Comment by Offerel** [comment]
Many thx for updating your request. Glad that you got it working.
