### ISSUE TITLE
CaldavZAP, roundcube and nextcloud ubuntu 20.04

### ISSUE THREAD

**Issue by francoisPE** [Offerel/roundcube_caldavzap#18]
Hello,

As I discussed a little bit on other issue, I try setup your very promising plugin.
Compared to previous discussion, to simplify, I decided to create login in nextcloud with mail address : that's much more simple and it works !

I try to connect but I don't succeed.
My brower says
cache_handler.min.js:1 Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at cache_handler.min.js:1
GET https://nextcloud.domain.tld/webmail/plugins/caldavzap/caldavzap_0.13.2/auth/?browser_date=20212021-avril-28&_=1619631327480 500 (Internal Error)

I have a cross domain setting.
I check login and password in both roundcube and nextcloud : there are the same

I set 
$config['caldav_server'] = 'nextcloud.domain.tld';

and try 
a. $config['caldav_path'] = '';   (should work, I have .wellknow conf)
b. $config['caldav_path'] = '/remote.php/dav/'; (what gives nextcloud)
c. $config['caldav_path'] = '/remote.php/dav/%u/calendars'; (why not !)

Nothing break the 500 !
Each time, I disconnect and connect in roundcube : not sure it's enough ?

is there any log file I can look at ?

many thanks

**Comment by Offerel** [comment]
a) is not supposed to work. There is no equivalent code in calcdavzap.

b) only works if there are only calendar resources on this URL. This depends on how your NextCloud is configured and how NextCloud or the web server rewrites the URL. I assume that this path will not work.

c) cannot work.

Since NextCloud partially overrides the web server rules and implements its own rules, it does not make things easier. You can try a path like "/remote.php/dav/calendars/". At least that would be what SabreDav uses in the basic configuration.  But I can't say for sure if this will work. If the placeholder for the username is before the caldav resource, this will not work. I have no idea, why NextCloud rewrites so much functional code, which makes using standard ways useless. Only someone will know the answer.

**Comment by francoisPE** [comment]
Thanks a lot for your advice.
I try
`$config['caldav_path'] = '/remote.php/dav/calendars/';`
following your above proposal. It is in line with https://nextcloud.com/blog/nextcloud-offers-caldav-synchronizer-for-outlook-users/
Also, I try `$config['caldav_path'] = '/remote.php/dav/calendars/%u';` following NC blog...
I modify also `$config['caldav_name'] = 'Personnel';` to be in line with agenda name...

Still same issue : internal 500 !

I check with thunderbird : I easily connect to that account...

**Comment by Offerel** [comment]
You should have a look on your php error logfile. Maybe you have a type in one of your files. Or PHP is not setup correct.

**Comment by francoisPE** [comment]
I finally find out error.log
`/usr/share/roundcube/plugins/caldavzap/caldavzap_0.13.2/errors.log`

it says 
`[29-Apr-2021 22:45:25 +0200]: DB Error: Configuration error. Unsupported database driver:  in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 85 (GET /webmail/plugins/caldavzap/caldavzap_0.13.2/auth/?browser_date=20212021-avril-29&_=1619729121585)`

I look in file  `/usr/share/roundcube/program/lib/Roundcube/rcube_db.php`
```
    /**
     * Factory, returns driver-specific instance of the class
     *
     * @param string $db_dsnw DSN for read/write operations
     * @param string $db_dsnr Optional DSN for read only operations
     * @param bool   $pconn   Enables persistent connections
     *
     * @return rcube_db Object instance
     */
    public static function factory($db_dsnw, $db_dsnr = '', $pconn = false)
    {
        $driver     = strtolower(substr($db_dsnw, 0, strpos($db_dsnw, ':')));
        $driver_map = array(
            'sqlite2' => 'sqlite',
            'sqlite3' => 'sqlite',
            'sybase'  => 'mssql',
            'dblib'   => 'mssql',
            'mysqli'  => 'mysql',
            'oci'     => 'oracle',
            'oci8'    => 'oracle',
        );

        $driver = isset($driver_map[$driver]) ? $driver_map[$driver] : $driver;
        $class  = "rcube_db_$driver";

        if (!$driver || !class_exists($class)) {
            rcube::raise_error(array('code' => 600, 'type' => 'db',
                'line' => __LINE__, 'file' => __FILE__,
                'message' => "Configuration error. Unsupported database driver: $driver"),
                true, true);
        }

        return new $class($db_dsnw, $db_dsnr, $pconn);
    }
```

My nextcloud is build with Mariadb... it should work mysqli is in !?
Do you already face such an issue ?

**Comment by francoisPE** [comment]
with `echo $driver $$driver_map`,
I saw that
`$driver=mysql ` 

so I add a line 
```
        $driver_map = array(
            'sqlite2' => 'sqlite',
            'sqlite3' => 'sqlite',
            'sybase'  => 'mssql',
            'dblib'   => 'mssql',
            'mysqli'  => 'mysql',
            'mysql'  => 'mysql',
            'oci'     => 'oracle',
            'oci8'    => 'oracle',
        );
```
rerun and see
`$driver=mysql ` 
and 
`$driver_map rcube_db_mysql `
No result !

I try more agressive 
`$driver='mysqli' ;`
Now log says 
```
 <pme9qe3m> DB Error: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 177 (GET /webmail/plugins/caldavzap/caldavzap_0.13.2/auth/?browser_date=20212021-avril-30&_=1619792206539)
``` 
I don't see where it can find connection data to mariadb...

Phpmyadmin shows
![image](https://user-images.githubusercontent.com/60675606/116708847-66ec8380-a9d0-11eb-8404-b168fdc23012.png)

**Comment by Offerel** [comment]
In my code there is nothing which should create a logfile in the plugin directory. If something is logged, this is written to the Roundcube logfile. There is no need to access a database from within my plugin. I use some values, which are saved in the Roundcube database itself.

Please check your Roundcube configuration, something must be miss-configured. You should never edit Roundcube's files besides the configuration files. There is no need to change the driver mapping. If you do that, you risk to loose the changes, if there is an update available either from Roundcube itself or any plugin.

**Comment by francoisPE** [comment]
I am very surprised (logging file directory, $driver value), but all I tell you is true.
I made changes in order to understand the issue not in order to make definitive changes...

In term of install, I have ubuntu 20.04, apt install with parameters :
  echo "roundcube-core roundcube/dbconfig-install boolean true" | debconf-set-selections
  echo "roundcube-core roundcube/database-type select mysql" | debconf-set-selections
  echo "roundcube-core roundcube/mysql/admin-pass password $CFG_MYSQL_ROOT_PWD" | debconf-set-selections
  echo "roundcube-core roundcube/db/dbname string roundcube" | debconf-set-selections
  echo "roundcube-core roundcube/mysql/app-pass password $CFG_ROUNDCUBE_PWD" | debconf-set-selections
  echo "roundcube-core roundcube/app-password-confirm password $CFG_ROUNDCUBE_PWD" | debconf-set-selections
  echo "roundcube-core roundcube/hosts string localhost" | debconf-set-selections
Next, I modify /etc/roundcube/config.inc.php file with smtp host and port... and add ispconfig plugins...
I suspect thise to be those that changed "error.log" location

I also integrate carddav plugin https://github.com/mstilkerich/rcmcarddav
May be there is an incompatibility...

I dig (so deep ;-)

**Comment by francoisPE** [comment]
I try deactivate all plugins except caldavzap, removing roundcube db content (user and sessions) 
No more effects...
Do you have ideas where to look at ?

**Comment by Offerel** [comment]
You can try to re-install from GitHub for both, Roundcube and the caldavzap plugin. I can only assume that there is somewhere a typo or miss configuration. and keep an eye on the logfiles, specially the Roundcube logs and php logs. Raise the log level. Maybe this could help to identify the issue.

**Comment by francoisPE** [comment]
Many thanks for your help.
I try fresh install and still turn into issues.
I forgive for the moment. 

Many thanks for your contribution to help me :-)
