### ISSUE TITLE
Don't work with Nextcloud calendar

### ISSUE THREAD

**Issue by raspifr** [Offerel/roundcube_caldavzap#3]
Hi,

This plugin doesn't work with my Nextcloud calendar.

I tried to configure config.js with the good informations but when I go to calendar nothing appears.

Roundcube is accessible with URL "https://local_mailserver_name:port" and Nextcloud with URL "https://local_cloudserver_name:port", so on 2 differents servers.

I use Roundcube & Nextcloud with those URL ONLY at home because I use phone application for each.

Than'ks for your help.

**Comment by Offerel** [comment]
A crossdomain setup is currently not supported. If the headers are set correctly on the remote server, it could work, but it does not have to. However, pull requests for a working setup are always welcome.

As a workaround I can only recommend a reverse proxy. It should work with that. For information on how to use a reverse proxy for your server, please refer to the documentation of your web server.

**Comment by raspifr** [comment]
I tried with reverse proxy : same result !!!

**Comment by Offerel** [comment]
when you say, you tested this with the reverse proxy, what do you get, when you browse to https://local_mailserver_name:port/nextcloud/path/calendars/username/ url with a webbrowser?

please provide the output of your browsers console.log, the network traffic log, your webserver error log and the roundcube error log files.

**Comment by raspifr** [comment]
roundcube error log:
_fsockopen(): unable to connect to ssl://my_domain.fr:443 (connexion refused)_

webserver error log:
_nothing_

When I try https://local_mailserver_name:port/nextcloud/path/calendars/username/ : 404.

**Comment by Offerel** [comment]
than thats your problem, you should fix this first. the first thing means: the connection is refused, either while the url is wrong or while a unsupported request was send.

the last one is a 404 error. 404 means normaly, that the target urls isn't found. 

Either you use the wrong url or something is missconfigured in your server.

**Comment by raspifr** [comment]
CalDavZap Config.js:

_var globalAccountSettings=[
{
    href: 'http://rnextcloud.my_domain.fr/', ("r" for "reverse")
    userAuth:
    {
        userName: 'user_nextcloud',
        userPassword: 'password_user_nextcloud'
    },
    timeOut: 90000,
    lockTimeOut: 10000,
    checkContentType: true,
    settingsAccount: true,
    delegation: true,
    hrefLabel: null,
    forceReadOnly: null,
    ignoreAlarms: false,
    backgroundCalendars: []
}
];_

I created on local_mailserver (where is Roundcube) a vhost apache with this configuration:

_<VirtualHost *:81>
                ServerName rnextcloud.my_domain.fr
                SSLProxyEngine On
                SSLProxyVerify none
                SSLProxyCheckPeerCN Off
                SSLProxyCheckPeerName Off
                SSLProxyCheckPeerExpire Off
                ProxyRequests Off
                ProxyPreserveHost On
                ProxyPass / https://local_cloudserver_name:port/remote.php/dav/calendars/ keepalive=On retry=5
                ProxyPassReverse / https://local_cloudserver_name:port/remote.php/dav/calendars/
</VirtualHost>_

On Config.php Nextcloud, I added:

_<?php
.....
"overwritewebroot"  => "/",
'trusted_proxies' => array ('IP_local_mailserver'),
'roundcube_nextcloud_des_key' => 'roundcube_des_key',
......
?>_

I tried several configurations but I don't find where is the problem...
:(:(

**Comment by Offerel** [comment]
config.js is the wrong settings file. Only config_rc.js is supported. The correct connector variable is globalNetworkRoundcubeSettings, but you use globalAccountSettings, This cant work with roundcube, since there is no connection between roundcube session and caldavzap.

Im not really sure, but i think the reverse proxy in your vhost is wrong configured. I think this should be configured as:
```
ProxyPass /nextcloud https://local_cloudserver_name:port/remote.php/dav keepalive=On retry=5
ProxyPassReverse /nextcloud https://local_cloudserver_name:port/remote.php/dav
```
then you should reach nextcloud with `https://local_mailserver_name:port/nextcloud/calendars/<username>` and username/password window should appear in your browser.

But im not really sure. Its a long time since i used the apache the last time.

**Comment by raspifr** [comment]
I modified vhost configuration:
- deleted "special" vhost (for reverseproxy)
- added proxy lines on roundcube vhost
- modified "/" by "/cal" and deleted after "/dav"

When I tried https://local_mailserver_name:port/cal/calendars/<username>, I obtain a 500 Internal Server Error.

Apache log:

_SSL Proxy requested for vhost_server_name:443 but not enabled [Hint: SSLProxyEngine]_

Strange because I don't use 443 port for webmail SSL, but another port... (???)

**Comment by raspifr** [comment]
I corrected differents SSL errors and now, I have a 502 Bad Gateway, who comes from nginx, so from my cloud_server...

**Comment by Offerel** [comment]
You should really fix your server problems first. 

If you can access the calendar in your browsers with https://local_mailserver_name:port/cal/calendars/ we can discuss the next problems here again.

**Comment by raspifr** [comment]
I don't know how works nginx... And it's nginx the problem...

**Comment by raspifr** [comment]
I don't understand why this issue was closed, the problem isn't resolved...
?????

**Comment by Offerel** [comment]
Your problem is a server problem, not a plugin problem. You should seek help from your admin or possibly in a server forum to get your configuration under control. Here I can only help with plugin problems.

**Comment by raspifr** [comment]
It's because YOUR plugin don't work "normally" (with or without crossdomain) that we must use a reverse proxy.
I think that it was very sympathetic to help users who need to make a reverse proxy while they not need otherwise.

**Comment by raspifr** [comment]
I have resolved my nginx problem !!!
Reverse proxy Apache to Nginx works now !!!
I tried the plugin... Don't work !!!

May I configure config.js or config_rc.js ?
May I use "globalAccountSettings" or other ?

**Comment by Offerel** [comment]
I'm glad you could solve the server problems.

As I wrote before, the correct config file is config_rc.js with the parameter globalNetworkRoundcubeSettings. Normally you don't have to change anything there. This is just a reference to the special roundcube connector for Caldavzap. The connector in turn reads the Roundcube Session variables and logs on to the CalDAV server via Basic Auth.

Only the config.inc.php of the Roundcube plugin has to be configured. For the time being, only the parameters caldav_server and caldav_path are important here. You have to adapt these to your domain and the path to the CalDAV server.

**Comment by raspifr** [comment]
OK.
But is it use the roundcube account to connect to caldav ?
Because Nextcloud calendar account isn't roundcube account...

I tried...
A dialog box ask me a user/password.

**Comment by Offerel** [comment]
Yes, it uses the same credentials as Roundcube, as I stated in the Readme. Otherwise it does not make any sense to re-use the Roundcube session variables.

**Comment by raspifr** [comment]
Well....
Thus it can't works, logically...
My roundcube account is my mail... But my nextcloud account is a "normal" cloud account, not a mail...
:(:(
Then, when I enter my roundcube account (my mail thus) with the good password, the dialog box re-appears. And when I enter my nextcloud account, it seems to be OK but I have an empty page, with just the refresh button.

**Comment by Offerel** [comment]
I don't know if you can change the Nextcloud user without to impact other things in Nextcloud. 

Nextcloud tries to do many things at the same time and does a lot of things only half-heartedly and most times quite badly. However, Nextcloud is based on SabreDAV and at least there it is relatively easy to change the user via the database, because all further calls are done by the ID's of the respective tables.

I cannot judge whether Nextcloud has changed much of this. I've removed Nextcloud again after discovering many useless SQL queries that only p artificially delay the queries, at least from my point of view.

You can only try to ask in a Nextcloud Forum, how username and password can be changed to match your Roundcube credentials.

**Comment by raspifr** [comment]
I created an nextcloud account with same name than roundcube account, thus my mail... OK.
I tried to go to "calendar" on roundcube, enter login/password of nextcloud account... KO.
I tried to go to "calendar" on roundcube, enter login/password of roundcube account... KO.

Nextcloud login and roundcube login is the same thus.
The nextcloud account password is different than the roundcube account password. Must it be the same ?

**Comment by Offerel** [comment]
"Credentials" is a synonym for the combination of username and password of account. And yes both must be exactly the same. The Nextcloud authentication should be set to "basic auth" and not to "digest auth" mechanism.

**Comment by raspifr** [comment]
Nextcloud account password modified to be the same of roundcube account... OK.
I tried to go to calendar... KO.

But I'm not sure of configuration...

* config.inc.php:
- $config['caldav_server'] ==> 'mailserver_name:port/cal/' ("cal" is used for apache proxy to do redirection to "https://cloud_server:port_for_proxy" who rewrite to "https://cloudserver:port/remote.php/dav/calendars/cloud_account" by nginx... It works when I try to go to this URL)

* config.js:
- Does I let "globalNetworkCheckSettings" like it is or does I modify it with "https://mailserver:port/cal/" ?

**Comment by Offerel** [comment]
You only need to change the file config.inc.php. You should set $config['caldav_server'] to your server without any folder. The folder must be configured with $config['caldav_path']. In your case it should work with:

```
$config['caldav_server'] = 'mailserver_name:port';
$config['caldav_path'] = '/cal/';
```

As i told before, config.js is not used with this plugin. 

I'm not sure if `https://cloudserver:port/remote.php/dav/calendars/cloud_account` is the correct target for the reverse proxy. But maybe it works, i don't know. In my opinion https://cloudserver:port/remote.php should be the target for the reverse proxy. If you change this to my example, you should also change `$config['caldav_path']` to `/cal/dav/calendars/;` if your local webserver is configured correct the new values could be:

```
$config['caldav_server'] = 'localhost:port';
$config['caldav_path'] = '/cal/dav/calendars/';
```

**Comment by raspifr** [comment]
I tried...

* 1:
$config['caldav_server'] = 'localhost:port';
$config['caldav_path'] = '/cal/;
==> Don't work !!! It seems to refuse my login/password, the box reappears...

* 2:
$config['caldav_server'] = 'localhost:port';
$config['caldav_path'] = '/cal/dav/calendars/;
rewrite nginx = https://cloudserver:port/remote.php
==> Don't work !!! It seems to refuse my login/password, the box reappears...

* 3:
$config['caldav_server'] = 'mailserver:port';
$config['caldav_path'] = '/cal/dav/calendars/;
rewrite nginx = https://cloudserver:port/remote.php
==> Don't work !!! It seems to refuse my login/password, the box reappears...

* 4:
$config['caldav_server'] = 'mailserver:port';
$config['caldav_path'] = '/cal/;
rewrite nginx = https://cloudserver:port/remote.php/dav/calendars/
==> Don't work !!! It seems to refuse my login/password, the box reappears...

* 5:
$config['caldav_server'] = 'localhost:port';
$config['caldav_path'] = '/cal/;
rewrite nginx = https://cloudserver:port/remote.php/dav/calendars/
==> Don't work !!! It seems to accept my login/password, the box don't reappears... But white page with just the refresh button...

No error message in apache log or nginx log !!!

**Comment by Offerel** [comment]
If it does not accept the username or password, then there absolutely MUST be a message in one of the logfiles. Otherwise your server is miss configured. You should check errors at the following places:

- Your browser webconsole
- roundcube error log on the local server
- webserver access log at the local server
- webserver error log at the local server
- logfile for php at the local server
- webserver access log at the remote server
- webserver error log at the remote server
- logfiles or error log on your nextcloud instance
- logfile for php on the remote server

And please do me a favor. Please solve the configuration problems with your server. There are hundreds of ways that can go wrong. With this really poor information, it is only one way of guessing where the needle might be hidden in the haystack. I can really only give you help with the plugin and not the server problems.

**Comment by raspifr** [comment]
Sorry, but there isn't server problem since yesterday. I've resolved it !!!
When I try directly the URL https://mailserver:port/cal/, it is redirected to https://cloudserver:port/remote.php/dav/calendars/ (the good webdav URL for Nextcloud) without any problem or error message !!! The box to login appears. I log in. I see "This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client." on the page, so it's OK for the URL. So the redirection and reverse proxy work !!!

I use Carddav plugin, it works without any problem, any box needed login/password !!!

The only erros I find it's Rouncube errors. And it is not server error messages, but indeed plugin error messages:

Peer certificate CN=`my.domain.fr' did not match expected CN=`localhost' in /path_to_roundcube/plugins/caldavzap/caldavzap_0.13.2/auth/plugins/roundcube.inc on line 33

Failed to enable crypto in /path_to_roundcube/plugins/caldavzap/caldavzap_0.13.2/auth/plugins/roundcube.inc on line 33

unable to connect to ssl://localhost:port (Unknown error) in /path_to_roundcube/plugins/caldavzap/caldavzap_0.13.2/auth/plugins/roundcube.inc on line 33

**Comment by raspifr** [comment]
I give up !!!
A not functional caldav with locals servers, what's the use. Like a simple calendar, without dav.
I am doing otherwise.
Bye

**Comment by francoisPE** [comment]
Hello,
I am back on that topic.
I am very interested in your plugin. It seems promising !
I read above discussion (quite webee !)

My nextcloud and roundcube are on same server !
The issue I see is : 
-> credential for
- roundcube = firstname.name@domain.tld + pswd
- nextcloud = firstname.name + pswd

Would you please tell me is it would be possible to 'cut' roundcube to go to nextcloud login ? 
If yes, would you please tell me where I can find it in code. 
I can fork your project and make that evolution...

Thanks a lot for your job 👍

**Comment by francoisPE** [comment]
Looking a little bit, I see in caldavzap_0.13.2/webdav_protocol.js, variable username... could be enough to change/cut it ?

**Comment by francoisPE** [comment]
line 227, adding that code at the end 

.split("@", 1)

what do you think ?

**Comment by Offerel** [comment]
The last version of CalDavZap is unfortunately incredibly old. I am using a beta version that is already newer than the official one, with a few additional bug fixes from me. But since the developers are still responding to questions, I wouldn't give up hoping for an updated version. For this reason, I would rather advise against changing anything in CalDavZap's files. This would unnecessarily complicate potential future updates. Access and authentication are done via a plug-in interface, check [roundcube.inc](https://github.com/Offerel/roundcube_caldavzap/blob/59e9b9328b17c1b9f1a261750894f31bd7214414/caldavzap_0.13.2/auth/plugins/roundcube.inc#L13). This is the better way, at least from my point of view.

BTW: You can also login to Nextcloud with your full email address. At least if i remember correctly, there was a config option for this some time ago. I have given up on NextCloud because of the huge performance issues and the way they force me to change my WebServer configuration.

**Comment by francoisPE** [comment]
Hello
thanks a lot for taking time answer me.
I understand that modifying CalDAVZAP is a bad idea.
I gonna investigate nextcloud login.
Your proposal is to modify roundcube.inc. [](https://github.com/Offerel/roundcube_caldavzap/blob/59e9b9328b17c1b9f1a261750894f31bd7214414/caldavzap_0.13.2/auth/plugins/roundcube.inc#L13[](url))
This $usr is login for caldav (nextcloud) or roundcube ? Not sure.
If caldav, I propose : 
$userR = $rcmail->user->get_username();
$user=$userR.split("@", 1);

What do you think ?

Regarding Nextcloud perfo, I think they improved a lot... a lot ! Security also
I have LAMP (apache24, PHP74, 8Gb RAM) it gives good result
