### ISSUE TITLE
Compatibility with elastic skin

### ISSUE THREAD

**Issue by madmath03** [Offerel/roundcube_caldavzap#5]
Hi,

Thanks for the plugin. Even though it does not suit my needs (cross domain configuration), it looks promising.
As such, I would suggest to add compatibility with Elastic Skin which is the new official skin starting with RoundCube 1.4: https://github.com/roundcube/roundcubemail/releases/tag/1.4-beta

**Comment by Offerel** [comment]
Hi there. I have changed the template and css, so that it should work with RC 1.4 now.
