### ISSUE TITLE
Wrong height on Elastic, Roundcube 1.4 beta, 

### ISSUE THREAD

**Issue by conathan** [Offerel/roundcube_caldavzap#7]
When testing this on the Roundcube 1.4 beta,  under elastic it was not the full height of the screen.

I worked around that by adding a style="height: 100%" to <div id="pluginbody"> in skins/elastic/templates/caldavzap.html

This is not a issue on the Larry/Classic skin (Larry looks like it uses position:absolute with top/left/right/bottom set to 0)

**Comment by Offerel** [comment]
Fix is in the new release
