### ISSUE TITLE
Can I use this with davical?

### ISSUE THREAD

**Issue by henrythemouse** [Offerel/roundcube_caldavzap#8]
The davical server and roundcube are both running on the same computer so I have both setups using localhost. I used localhost in the caldavzap config. When I try to load the calendar a page is loaded that displays the caldavzap refresh button on the left side. An authentication popup dialog pops up asking me to login:

`http://serverhostname is requesting your username and password. The site says: “Inf-IT Auth Module”`

I'm accessing the server from a laptop on the my home network, that's why I'm using 'serverhostname' instead of localhost in the url. I also access roundcube from remote locations using a DDNS provider. I don't get any errors in roundcube's errors.log or apache's error.log.

I use infcloud in a seperate installation, in case that matters.

Any help would be appreciated, this is a great calendar application and I'd like to use it in roundcube.

TIA

**Comment by Offerel** [comment]
In theory, it should work with any CalDAV backend, but i couldnt test it with davical. If you want, you can send me your configs (config.inc and all other customizations). If you say you use infcloud in a seperate installation, this config is also from interest for me. Maybe i have something i have to change in the plugin to get it to work.

**Comment by henrythemouse** [comment]
I'll get this together and post it here soon. Thanks for the offer to help.

**Comment by henrythemouse** [comment]
> In theory, it should work with any CalDAV backend, but i couldnt test it with davical. If you want, you can send me your configs (config.inc and all other customizations). If you say you use infcloud in a seperate installation, this config is also from interest for me. Maybe i have something i have to change in the plugin to get it to work.

I am using rc 1.4-rc1.

While I have tried some customizations to the your caldavzap config.js in the top line (var globalNetworkCheckSettings=), the script never got that far, always failing to authenticate.
So, I've returned that to it's original state. I've also tried to hard code the variables in roundcube.inc line 33 ($fp=fsockopen($hostname, $port, $errno, $errstr, $pluginconfig['timeout']);) trying to find a combination that would look like what I'm used to looking at when setting up access to a davical calendar. I had no luck with that effort either. That file is back to it's original state. 

Typically I access the davical server with a url like this:
`https://hostname.domain.com/caldav.php/username/calendar/`
which works with the other rc calendar plugin called calendar and gnome calendar, but doesn't tell me anything about how they authenticate.

As you can tell by my infcloud config.js below I haven't made any significant changes from the original author's config.js. He states that when using davical, infcloud will work out of the box as long as it is installed in the davical htdocs directory without any modifications to config.js. It always has for me. If I can provide any more information that might help I'd be happy to do that.

Thank you.

[rc-zap-config.inc.php.txt](https://github.com/Offerel/roundcube_caldavzap/files/3632454/rc-zap-config.inc.php.txt)

[my-inf-config.js.txt](https://github.com/Offerel/roundcube_caldavzap/files/3632433/my-inf-config.js.txt)

**Comment by henrythemouse** [comment]
Looks like the situation has changed, or should I say I made a mistake.
After taking a second look at the files I sent you I realized that the file path was not correct in caldavzap's config.inc.php. I corrected that. I also upgraded rc to 1.4-rc2 and enabled the new elastic theme. 

The popup authentication dialog still comes up,  but if I cancel it some of the calendar page shows. More of it shows in elastic than in the other themes. So it seems to me that perhaps caldavzap is authenticating, yet the calendar is not fully displaying. I took two screenshots, elastic and classic themes.

Thank you
![rc-caldavzap-classic](https://user-images.githubusercontent.com/11880699/65273558-43641600-dad6-11e9-8776-2bac19038f1b.png)
![rc-caldavzap-elastic](https://user-images.githubusercontent.com/11880699/65273559-43641600-dad6-11e9-99ac-e50202ee5623.png)

**Comment by Offerel** [comment]
I will have a look at the weekend. It seems that RC1. 4 RC 2 has changed many things between RC 1 and RC 2. I have to change again all my plugins. 

Additionally, it seems that the calendar isn't authenticated completely.

I will try to get it to work.

**Comment by henrythemouse** [comment]
I see that you've closed this issue. I'm curious, have you determined that your plugin will not work with davical? Maybe you don't have the time to pursue this? Or is there some other reason why you've closed this issue?

Thank you

**Comment by Offerel** [comment]
Hi. From your last comment I had guessed that one of your configuration files had caused the problem and now only the problem with display exists. Therefore I released a new version today. It took a bit longer, because my Raspberry Pi was not working that well.

Sorry if I misunderstood. If I misunderstood you, can you please reopen the issue?

**Comment by henrythemouse** [comment]
> I am unable to reopen this issue, I believe that the rules are that only the person that closed the issue can reopen it. We can proceed by comments only, if you prefer not to reopen it.

Hi,
I'd say that the ui is much improved and not a problem at this point. Most likely I have an authentication problem. I'm wondering if you could help with that problem. I'll post my caldavzap config and an update picture of the ui. I'm thinking that I shouldn't be editing any of the caldavzap internal files. I am certain that the credentials for RC are the same as the credentials for the davical server. 

Any suggestions as to how I could proceed would be very welcome.
TIA

![caldavzapRC](https://user-images.githubusercontent.com/11880699/66520673-76c70e80-ea9e-11e9-8001-4d8eb7baf5dd.png)

[config.inc.php.txt](https://github.com/Offerel/roundcube_caldavzap/files/3709442/config.inc.php.txt)

**Comment by henrythemouse** [comment]
I am getting a couple of errors in the rc errors.log.

```
rc error log
[09-Oct-2019 15:59:21] PHP Warning:  fsockopen(): Failed to enable crypto in ...caldavzap/caldavzap_0.13.2/auth/plugins/roundcube.inc on line 33

[09-Oct-2019 15:59:21] PHP Warning:  fsockopen(): unable to connect to ssl://localhost:443 (Unknown error) ...caldavzap/caldavzap_0.13.2/auth/plugins/roundcube.inc on line 33

```
The ssl:/localhost doesn't look right to me as the rc hostname is just localhost.

**Comment by henrythemouse** [comment]
I noticed this code in roundcube_config.inc, which does mention davical. Not knowing much about php I really don't know what it could be doing or not.

```
<?php
        define('INSTALL_PATH', realpath(__DIR__ . '/../../../../') . '/');
        require_once INSTALL_PATH . 'program/include/iniset.php';
        $rcmail = rcmail::get_instance();

        // Server base URL
        $pluginconfig['base_url']=(empty($_SERVER['HTTPS']) ? 'http' : 'https').'://'.$rcmail->config->get('caldav_server');

        // Default values are usually OK
        //  for Davical:
        $pluginconfig['request']=$rcmail->config->get('caldav_path', false);    // change only if your Davical is not installed into server root directory
        //  for Lion server:
        //$pluginconfig['request']='/principals/users';

        $pluginconfig['timeout']=30;
?>
```

**Comment by henrythemouse** [comment]
I've contacted the davical mailing list for help.

**Comment by Offerel** [comment]
According to your error message, i assume that your davical instance is on the same host as your Roundcube instance. Davical is in this case on a localhost webserver secured with SSL on port 443.

In most cases "fsockopen(): Failed to enable crypto" means, that php cant handle the configured cipher suites for your davical at localhost:443.

This leads me to some questions. Do you really need to encrypt the data if you only pull them at your local network? If not, then use davical on a unencrypted server. 

If you really need the data encrypted, make sure that you configure a cipher suite at the davical server, which is usable by your php interpreter. There was some changes where old and poor cipher suites are not supported anymore.

**Comment by henrythemouse** [comment]
I'm not sure I can answer your questions, but I'll try. I had to search for 'cipher suites' to find out what that meant. As far as I know they are handled in the ssl module for apache. I haven't modified that file at all. 

Davical  is a set of php scripts that access data stored in postgres and I haven't found any davical code that might help fix this yet. I'll keep looking.

You're right in that I may not  need more encryption, I access this calendar using https://my.dydns.tld using a letsencrypt cert. In other words the domain is not assigned to a static ip. The transfer is always encrypted by that connection (I think?). The trouble might be that the caldavzap plugin (or rc itself) is having an issue with this setup. I found another line in the errors.log:

`[11-Oct-2019 11:44:30] PHP Warning:  fsockopen(): Peer certificate CN=*.dydns.tld did not match expected CN=localhost in /var/www/roundcubemail-1.4-rc2/plugins/caldavzap/caldavzap_0.13.2/auth/plugins/roundcube.inc on line 33`

Perhaps because I have a virtualhost configured to use  my letsencrypt cert, php is wanting the same CN to access caldavzap? As I've said earlier , I don't get that issue when using infCloud, so could that mean it is something in rc that is causing this to come up?

I'm probably in over my head .
Thanks again for your input.

**Comment by Offerel** [comment]
No prob. I try to explain in a high level format. When you use Infcloud you insert https://my.dyndns.tld in your browser which matches the CN part of your let's encrypt cert. Thats why it works. Roundcube on the other side is configured to use localhost, which is not part of your CN in your cert. Thats why this connection failed. Additionally I assume you didn't use a modern cipher suite. The last PHP versions have removed support for some insecure cipher suites.

To fix both problems, i would recommend that you create a new vhost sharing the same davical backend, but this new vhost should be configured only to work inside your local network and not from outside. With that you can use port 80 without SSL certificate and cipher suites. Just make sure that this vhost can't be reached from outside.

I'm not familiar with Apache config, since i use Nginx, but i know its not that difficult.

**Comment by henrythemouse** [comment]
Thank you. Your local network suggestion not only worked, but it pointed me to the correct solution for accessing the calendar remotely using my domain. I figured that if it worked to get rc to use localhost so it would match the davical localhost then it should work to get davical to use my remote domain name to match rc using the remote domain name. 

It took a while to get the pieces set up correctly, but it was fairly straight forward using the local setup as a map. I wish I didn't have to take up so much of your time, it was generous of you to take the time to help.

Thank you

**Comment by Offerel** [comment]
No prob. I'm always happy when I can truly help. Sometimes it's not easy because there can be so many different configurations. It makes me even happier when it really works.
